config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users do
    member do
      post :follow_user, as: 'follow'
      get :notification, as: 'notify'
      get :timeline, as: 'timeline'
    end
  end

  namespace :admin do
    resources :images
    resources :users do
      member do
        post :disable_user, as: 'disable'
      end
    end
  end
  resources :images do
    collection do
      get :my_images
      get :public_images
    end
    member do
      post :like
    end
  end

  resources :albums, except: [:index] do
    collection do
      get :my_albums, as: 'my_albums'
      get :public_albums, as: 'public_albums'

    end
    member do
      post :like
      post :follow_album, as: 'follow'
    end
    resources :images, only: [:index, :create, :new]
  end

  resources :statuses do
    member do
      post :like
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums, dependent: :destroy
  has_many :images
  has_many :likes
  has_many :follows, as: :followable
  has_many :followers, through: :follows, source: :user
  has_many :notifications
  has_many :histories, as: :itemable
  has_many :statuses

  # check permission for user

  def active_for_authentication?
    #remember to call the super
    #then put our own check to determine "active" state using
    #our own "is_active" column
    super and self.is_active?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :get_user ,only: [ :disable_user, :destroy]
  before_action :init_service

  def index
    @page, @per_page, @users = @user_service.get_users_list params
  end

  def new
    @user = User.new
  end

    # POST/users
    #POST/users.json

  def disable_user
    @user_service.disable_user @user
    redirect_to admin_users_path
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def init_service
    @user_service ||= UserService.new
  end

  def user_params
    params.require(:user).permit(:avatar)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'
  before_action :init_service
  def show

  end

  def timeline
    @status = Status.new
    @histories = @history_service.get_histories params
  end

  def follow_user
    @object = User.find(params[:object_id])
    @follow_service.follow(@object)
    if @follow_service.check_follow? @object
      @notify_service.create_notification(current_user,"follow_user",
    @object)
    end
    redirect_to root_path
  end

  def notification
    @page,@per_page,@notifications = @notify_service.get_notification_list params
  end

  private
  def init_service
    @follow_service ||= FollowService.new(current_user)
    @notify_service ||= NotificationService.new(current_user)
    @history_service ||= HistoryService.new(current_user)
  end
end

app/views/users/notification.html.slim
h1
  | Notifications
table.table.table-bordered
  tr
    td = I18n.t("table.notification.no_")
    td = I18n.t("table.notification.created_at")
    td = I18n.t("table.notification.content")
    td = I18n.t("table.notification.people_involved")
    td = I18n.t("table.notification.delete")
    td = I18n.t("table.notification.unfollow")
  - @notifications.each_with_index do |notification,index|

    tr
      td
        = ((@page - 1) * @per_page) + (index + 1)
      td
        = notification.created_at.strftime("%d/%m/%Y")
      td
        = notification.content
      td
        = notification.objecter.first_name
      td
        = link_to(I18n.t("table.notification.delete"))
        / ,admin_image_path(image),method: :delete, data: { confirm: I18n.t("table.image.confirm.delete")})
      td
        = link_to(I18n.t("table.notification.unfollow"))

  = paginate @notifications

app/views/users/show.html.slim
.sidebar-section.about-author.center-text
  .author-image
    = image_tag "/assets/charlie.png", class: "profile"

  h4.author-name
    b.light-color
      | Cristine Smith
  p
    | Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque dolore magnam aliquam quaerat voluptatem.
  .signature-image
    = image_tag "/assets/sign.png"
  a.read-more-link[href="#"]
    b
      | READ MORE

app/views/users/timeline.html.slim
.row
  .col-sm-8
    .well
      = form_for @status, html: {class: "form-horizontal"} do |f|
        h4
          = I18n.t("title.user.what_new")
        .form-group.padding
          = f.text_area(:content, class: "form-control",placeholder: I18n.t("title.user.update_your_status"))
        button.btn.btn-primary.pull-right[type="submit"]
                = I18n.t("title.user.post")
        ul.list-inline
          li
            a[href=""]
              i.glyphicon.glyphicon-upload
          li
            a[href=""]
              i.glyphicon.glyphicon-camera
          li
            a[href=""]
              i.glyphicon.glyphicon-map-marker
    - @histories.each do |item|
      - if item.itemable_type == "Album"
        .panel.panel-default
          .well
            p
              img[src="/assets/user.png" height="28px" width="28px"]
              - image = item.itemable.images.first
              dt.text-capitalize
                = " " + item.itemable.user.first_name + " "
                = "has created a new album"
              p
                = item.itemable.created_at.strftime("%d/%M/%Y %H hours")
              i.fa.fa-globe
            .panel-thumbnail.image
              / img.img-responsive[src="/assets/bg_4.jpg"]
              = image_tag image.image.url,class: "img-responsive"
              h2
                - if((item.itemable.images.count - 1) == 0 )
                  = " "
                - else
                  = link_to "+" + (item.itemable.images.count - 1).to_s, album_path(item.itemable)
            .panel-body
              p.lead
                = item.itemable.title
            = image_tag "heart.png", class: "img-heart"
            = " " + item.itemable.likes.count.to_s
          .btn-group
            = link_to(I18n.t("title.user.share"),"",class: "btn-timeline btn-primary pull-right")
            = link_to(I18n.t("title.user.comment"),"",class: "btn-timeline btn-primary pull-right")
            = link_to(like_album_path(item.itemable,show: "timeline_album"), method: :like, class: "btn-timeline btn-primary pull-right")
              i.glyphicon.glyphicon-thumbs-up
              = I18n.t("title.user.like")



      - elsif item.itemable_type == "Image"
        .panel.panel-default.image
          .well
            p
              img[src="/assets/user.png" height="28px" width="28px"]
              dt.text-capitalize
                = " " + item.itemable.user.first_name + " "
                = "has created a new image"
              p
                = item.itemable.created_at.strftime("%d/%M/%Y %H hours")
              i.fa.fa-globe
            .panel-thumbnail
              / img.img-responsive[src="/assets/bg_4.jpg"]
              = image_tag item.itemable.image.url,class: "img-responsive"
            .panel-body
              p.lead
                = item.itemable.title
            = image_tag "heart.png", class: "img-heart"
            = " " + item.itemable.likes.count.to_s
          .btn-group
            = link_to(I18n.t("title.user.share"),"",class: "btn-timeline btn-primary pull-right")

            = link_to(I18n.t("title.user.comment"),"",class: "btn-timeline btn-primary pull-right")

            = link_to(like_image_path(item.itemable,show: "timeline_image"), method: :like, class: "btn-timeline btn-primary pull-right")
              i.glyphicon.glyphicon-thumbs-up
              = I18n.t("title.user.like")
      - else
        .panel.panel-default
          .well
            p
              img[src="/assets/user.png" height="28px" width="28px"]
              dt.text-capitalize
                = " " + item.itemable.user.first_name + " "
                = "has created a new status"
              p
                = item.itemable.created_at.strftime("%d/%M/%Y %H hours")
              i.fa.fa-globe
            .panel-body
              p.lead
                = item.itemable.content
            = image_tag "heart.png", class: "img-heart"
            = " " + item.itemable.likes.count.to_s
          .btn-group
            = link_to(I18n.t("title.user.share"),"",class: "btn-timeline btn-primary pull-right")
            = link_to(I18n.t("title.user.comment"),"",class: "btn-timeline btn-primary pull-right")
            = link_to(like_status_path(item.itemable,show: "timeline_status"), method: :like, class: "btn-timeline btn-primary pull-right")
              i.glyphicon.glyphicon-thumbs-up
              = I18n.t("title.user.like")


    = paginate @histories

  .col-sm-4
    .panel.panel-default
      .panel-heading
        a.pull-right[href="#"]
          = I18n.t("title.user.view_all")
        h4
          = I18n.t("title.user.news")
      .panel-body
        img.img-circle.pull-right[src="/assets/150x150.gif"]
        a[href="#"]
          | Journalist
        .clearfix
        hr
        p
          | Today I miss
          code
            | Thao Vi


        hr
        form
          .input-group
            .input-group-btn
            input.form-control[placeholder="Add a comment.." type="text"]