config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users do
    member do
      post :follow_user, as: 'follow'
      get :notification, as: 'notify'
      get :timeline, as: 'timeline'
    end
  end

  namespace :admin do
    resources :images
    resources :users do
      member do
        post :disable_user, as: 'disable'
      end
    end
  end
  resources :images do
    collection do
      get :my_images
      get :public_images
    end
    member do
      post :like
    end
  end

  resources :albums, except: [:index] do
    collection do
      get :my_albums, as: 'my_albums'
      get :public_albums, as: 'public_albums'

    end
    member do
      post :like
      post :follow_album, as: 'follow'
    end
    resources :images, only: [:index, :create, :new]
  end

  resources :statuses do
    member do
      post :like
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_show_albums.html.slim
.span9
  ul.thumbnails.listing-products
    - albums.each do |album|
      li.span3
        .product-box
          span.sale_tag
          = link_to album_path(album)
            - if album.images.first.present?
              - image = album.images.first
              = image_tag(image.image.url(:thumb))
          br
          a.title[href="#"]
            = album.title
          br
          a.category[href="#"]
            = album.description
          p.price
            = I18n.t("title.album.total_images")
            = album.images.count
          p.price
              = album.user.first_name

          = link_to album.likes.count, "", class: "btn btn-default"
          - if params[:action] == "public_albums"
            = link_to like_album_path(album, show: "public_albums"),method: :like, class: "btn btn-default"
              i.glyphicon.glyphicon-heart
            - if album.follows.where(user_id:current_user.id).present?
              = link_to follow_album_path(album), method: :follow_album, class: "btn btn-default"
                i.glyphicon.glyphicon-eye-close
            -else
              = link_to follow_album_path(album), method: :follow_album, class: "btn btn-default"
                i.glyphicon.glyphicon-eye-open
          - else
            = link_to like_album_path(album, show: "my_albums"),method: :like, class: "btn btn-default"
                i.glyphicon.glyphicon-heart
          - if album.user.id == current_user.id
            = link_to edit_album_path(album), class: "btn btn-default"
                i.glyphicon.glyphicon-pencil
            = link_to album_path(album),method: :delete,data: { confirm: I18n.t("table.album.confirm.delete")}, class: "btn btn-default"
                i.glyphicon.glyphicon-remove

app/views/shared/_show_images.html.slim
.span9
    ul.thumbnails.listing-products
      - images.each do |image|
        li.span3
          .product-box
            span.sale_tag
            = link_to image_path(image)
              = image_tag image.image.url(:thumb)
            br
            a.title[href="#"]
              = image.title
            br
            a.category[href="#"]
              = image.description
            p.price
              = image.user.first_name
            = link_to image.likes.count,"", class: "btn btn-default"
            - if params[:action] == "public_images"
              = link_to like_image_path(image, show: "public_images"),method: :like, class: "btn btn-default"
                i.glyphicon.glyphicon-heart
            - else
              = link_to like_image_path(image),method: :like, class: "btn btn-default"
                i.glyphicon.glyphicon-heart

            - if image.user.id == current_user.id
              = link_to edit_image_path(image),class: "btn btn-default"
                  i.glyphicon.glyphicon-pencil
              = link_to image_path(image),method: :delete,data: { confirm: "Are you sure ?"},class: "btn btn-default"
                  i.glyphicon.glyphicon-remove