config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users do
    member do
      post :follow_user, as: 'follow'
      get :notification, as: 'notify'
      get :timeline, as: 'timeline'
    end
  end

  namespace :admin do
    resources :images
    resources :users do
      member do
        post :disable_user, as: 'disable'
      end
    end
  end
  resources :images do
    collection do
      get :my_images
      get :public_images
    end
    member do
      post :like
    end
  end

  resources :albums, except: [:index] do
    collection do
      get :my_albums, as: 'my_albums'
      get :public_albums, as: 'public_albums'

    end
    member do
      post :like
      post :follow_album, as: 'follow'
    end
    resources :images, only: [:index, :create, :new]
  end

  resources :statuses do
    member do
      post :like
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user, optional: true
  has_many :images, dependent: :destroy
  has_many :likes , as: :likeable
  has_many :follows, as: :followable
  has_many :followers, through: :follows, source: :user
  has_many :histories, as: :itemable



end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  layout 'user'
  before_action :authorize_album!, only: [:edit, :update, :destroy]
  before_action :get_album, only: [:like,:follow_album]
  before_action :init_service

  def my_albums
    @albums = @album_service.get_albums params
  end

  def public_albums
    @albums = @album_service.get_albums params
  end

  def new
    @album = Album.new
  end

  def show
    if Album.exists?(id: params[:id])
      @album = Album.find(params[:id])
    else
      @image = Image.find params[:id]
      @album = @image.album
    end
    @images = @album.images.page(params[:page]).per(12).order(id: :desc)
    @count = @album.images.page(params[:page]).per(12)
  end

  def create
    @album = @album_service.create_album params,album_params
    redirect_to my_albums_albums_path(@album)
  end

  def edit

  end

  def update
    @album_service.update_album(@album,album_params)
    redirect_to  my_albums_albums_path
  end

  def like
    @album_service.like_album @album
    if params[:show] == "public_albums"
      redirect_to public_albums_albums_path
    elsif params[:show] == "timeline_album"
      redirect_to timeline_user_path(current_user)
    else
      redirect_to my_albums_albums_path
    end
  end

  def follow_album
    @follow_service.follow @album
    if @follow_service.check_follow? @object
      @notify_service.create_notification(current_user,"follow_album",
    @object)
    end
    redirect_to public_albums_albums_path
  end

  def destroy
    @album_service.delete_album @album
    redirect_to my_albums_albums_path
  end

  private
  def authorize_album!
    @album = current_user.albums.find_by_id(params[:id])
    redirect_to(root_path, alert: I18n.t("album.permission")) unless @album
  end

  def init_service
    @album_service ||= AlbumService.new(current_user)
    @follow_service ||= FollowService.new(current_user)
  end

  def album_params
    params.require(:album).permit(:title, :description, :is_private)
  end

  def get_album
    @album = Album.find params[:id]
  end
end

app/views/albums/_form.html.slim
= form_for @album, html: { multipart: true } do |f|
  .form-group.col-sm-8
    = f.label(:title)
    = f.text_field(:title, class: "form-control")
  .form-group.col-sm-8
    = f.label(:description)
    = f.text_area(:description, class: "form-control")
  - if album.new_record?
    .form-group.col-sm-8
      = f.label(:image)
      = f.file_field(:image, class: "form-control", multiple:true)
  .form-group.col-sm-8
    = f.label(:is_private)
    br
    = f.check_box(:is_private)
  button.btn.btn-primary.btn-lg[type="submit"]
    = I18n.t("title.album.button.save")

app/views/albums/edit.html.slim
h1
  =I18n.t("title.album.edit")
= render "form", album: @album

app/views/albums/index.html.slim
h1
  = I18n.t("title.album.list")

.btn.btn-default[type="button"]
  = link_to I18n.t("title.album.button.create"), new_user_album_path
hr
table.table.table-bordered
  tr
    td = I18n.t("table.album.no_")
    td = I18n.t("table.album.title")
    td = I18n.t("table.album.description")
    td = I18n.t("table.album.private")
    td #
    td #
    td #
  - @albums.each do |album|
    tr
      td
        = album.id
      td
        = album.title
      td
        = album.description
      td
        - if album.is_private
          = "Private"
        - else
          = "Public"
      td
        =link_to I18n.t("table.album.view_images"), album_images_path(album)
      td
        =link_to I18n.t("table.album.edit"),edit_user_album_path(current_user.id,album.id)
      td
        = link_to I18n.t("table.album.delete"), [current_user,album], method: :delete, data: { confirm:I18n.t("table.album.confirm.delete") }
= paginate @albums

app/views/albums/my_albums.html.slim
h1
  = I18n.t("title.album.my_albums")
hr
.btn.btn-default[type="button"]
  = link_to I18n.t("title.album.button.create"), new_album_path
hr
= render "shared/show_albums", albums: @albums
= paginate @albums

app/views/albums/new.html.slim
h1
  = I18n.t("title.album.create")
= render "form", album: @album

app/views/albums/public_albums.html.slim
h1
  = I18n.t("title.album.public_albums")
hr
= render "shared/show_albums", albums: @albums

= paginate @albums

app/views/albums/show.html.slim
h1
  = I18n.t("title.album.show")

h3
  = I18n.t("table.album.title")
  = @album.title
h3
  = I18n.t("table.album.description")
  = @album.description

hr
  = render "shared/show_images", images: @images
= paginate @images