config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users do
    member do
      post :follow_user, as: 'follow'
      get :notification, as: 'notify'
      get :timeline, as: 'timeline'
    end
  end

  namespace :admin do
    resources :images
    resources :users do
      member do
        post :disable_user, as: 'disable'
      end
    end
  end
  resources :images do
    collection do
      get :my_images
      get :public_images
    end
    member do
      post :like
    end
  end

  resources :albums, except: [:index] do
    collection do
      get :my_albums, as: 'my_albums'
      get :public_albums, as: 'public_albums'

    end
    member do
      post :like
      post :follow_album, as: 'follow'
    end
    resources :images, only: [:index, :create, :new]
  end

  resources :statuses do
    member do
      post :like
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="content-type" /
    meta charset="utf-8" /
    title = I18n.t("title.web")
    meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport" /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .wrapper
      .box
        .row.row-offcanvas.row-offcanvas-left
          /! sidebar
          #sidebar.column.col-sm-2.col-xs-1.sidebar-offcanvas
            ul.nav.nav-list.below
              li
                a.visible-xs.text-center data-toggle="offcanvas" href="#"
                  i.glyphicon.glyphicon-chevron-right
            ul#lg-menu.nav.hidden-xs
              li.actnav.nav-list
                h4
                  i.glyphicon.glyphicon-list-alt
                    = link_to I18n.t("admin.profile")
              li
                h4
                  .glyphicon.glyphicon-list-alt
                    = link_to I18n.t("admin.images"), admin_images_path

              li
                  h4
                    .glyphicon.glyphicon-list-alt
                    = link_to I18n.t("admin.user"),admin_users_path
              li
                  h4
                    = link_to I18n.t("log_out"), destroy_user_session_path, method: :delete
            ul#sidebar-footer.list-unstyled.hidden-xs
              li
                h3 = I18n.t("admin.title")
                i.glyphicon.glyphicon-heart-empty
                = I18n.t("admin.director")
            /! tiny only nav
            ul#xs-menu.nav.visible-xs
              li
                a.text-center href="#featured"
                  i.glyphicon.glyphicon-list-alt
              li
                a.text-center href="#stories"
                  i.glyphicon.glyphicon-list
              li
                a.text-center href="#"
                  i.glyphicon.glyphicon-paperclip
              li
                a.text-center href="#"
                  i.glyphicon.glyphicon-refresh
          /! /sidebar
          /! main right col

          #main.column.col-sm-10.col-xs-11
            .panel-body
              = yield

    /! post modal

    javascript:
      $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
        $(this).toggleClass('visible-xs text-center');
        $(this).find('i').toggleClass('glyphicon-chevron-right glyphicon-chevron-left');
        $('.row-offcanvas').toggleClass('active');
        $('#lg-menu').toggleClass('hidden-xs').toggleClass('visible-xs');
        $('#xs-menu').toggleClass('visible-xs').toggleClass('hidden-xs');
        $('#btnShow').toggle();
        });
      });

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Final App
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/user.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="content-type" /
    meta charset="utf-8" /
    title = I18n.t("title.web")
    meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport" /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .wrapper
      .box
        .row.row-offcanvas.row-offcanvas-left
          /! sidebar
          #sidebar.column.col-sm-2.col-xs-1.sidebar-offcanvas
            ul.nav.nav-list.below
              li
                a.visible-xs.text-center data-toggle="offcanvas" href="#"
                  i.glyphicon.glyphicon-chevron-right
            ul#lg-menu.nav.hidden-xs
              li.actnav.nav-list
                h4
                  i.glyphicon.glyphicon-heart-empty
                    = link_to I18n.t("title.user.timeline"), timeline_user_path(current_user)
              li.actnav.nav-list
                h4
                  i.glyphicon.glyphicon-heart-empty
                    = link_to I18n.t("title.user.notify"), notify_user_path(current_user)
              li.actnav.nav-list
                h4
                  i.glyphicon.glyphicon-heart-empty
                    = link_to I18n.t("title.user.following")
              li.actnav.nav-list
                h4
                  i.glyphicon.glyphicon-heart-empty
                    = link_to I18n.t("title.user.follower")
              li.actnav.nav-list
                h4
                  i.glyphicon.glyphicon-user
                    = link_to I18n.t("user.profile"),root_path
              li.actnav.nav-list
                h4
                  i.glyphicon.glyphicon-heart-empty
                    = link_to I18n.t("user.albums")
                  h5
                  ul.nav.nav-list.below
                    li
                      = link_to I18n.t("user.my_albums") ,my_albums_albums_path
                    li
                      = link_to I18n.t("user.public_albums"),public_albums_albums_path
              li
                h4
                  i.glyphicon.glyphicon-star-empty
                    = link_to I18n.t("user.images")
                h5
                  ul.nav.nav-list.below
                    li
                      = link_to I18n.t("user.my_images") ,my_images_images_path
                    li
                      = link_to I18n.t("user.public_images") ,public_images_images_path

            ul#sidebar-footer.list-unstyled.hidden-xs
              li
                a href="http://usebootstrap.com/theme/facebook" /
                h3 = I18n.t("admin.title")
                i.glyphicon.glyphicon-heart-empty
                  = I18n.t("admin.director")
            /! tiny only nav
            ul#xs-menu.nav.visible-xs
              li
                a.text-center href="#featured"
                  i.glyphicon.glyphicon-list-alt
              li
                a.text-center href="#stories"
                  i.glyphicon.glyphicon-list
              li
                a.text-center href="#"
                  i.glyphicon.glyphicon-paperclip
              li
                a.text-center href="#"
                  i.glyphicon.glyphicon-refresh
          /! /sidebar
          /! main right col

          #main.column.col-sm-10.col-xs-11
            .navbar.navbar-blue.navbar-static-top
              .navbar-header
                button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
                a.navbar-brand.logo
                  = I18n.t("title.user.logo")
              nav.collapse.navbar-collapse[role="navigation"]
                form.navbar-form.navbar-left
                  .input-group.input-group-sm[style="max-width:360px;"]
                    input#srch-term.form-control[placeholder="Search" name="srch-term" type="text"]
                    .input-group-btn
                      button.btn.btn-default[type="submit"]
                        i.glyphicon.glyphicon-search
                ul.nav.navbar-nav
                  li
                    a[href="#"]
                      i.glyphicon.glyphicon-home
                      = " " + I18n.t("title.user.home")
                  li
                    a[href="#postModal" role="button" data-toggle="modal"]
                      i.glyphicon.glyphicon-plus
                      = " " + I18n.t("title.user.post")
                  li
                    a[href="#"]
                      span.badge
                        = I18n.t("title.user.group")
                ul.nav.navbar-nav.navbar-right
                  li.dropdown
                    a.dropdown-toggle[href="#" data-toggle="dropdown"]
                      i.glyphicon.glyphicon-user
                    ul.dropdown-menu
                      li
                        a[href=""]
                          | Log out
                      li
                        a[href=""]
                          | Change your password
                      li
                        a[href=""]
                          | Settings
            .panel-body
              .padding
                .full.col-sm-9
                  .row
                    = yield

    #postModal.modal.fade[tabindex="-1" role="dialog" aria-hidden="true"]
      .modal-dialog
        .modal-content
          .modal-header
            button.close[type="button" data-dismiss="modal" aria-hidden="true"]
              | ×
            |  Update Status
          .modal-body
            form.form.center-block
              .form-group
                textarea.form-control.input-lg[autofocus="" placeholder="What do you want to share?"]
          .modal-footer
            div
              button.btn.btn-primary.btn-sm[data-dismiss="modal" aria-hidden="true"]
                | Post
              ul.pull-left.list-inline
                li
                  a[href=""]
                    i.glyphicon.glyphicon-upload
                li
                  a[href=""]
                    i.glyphicon.glyphicon-camera
                li
                  a[href=""]
                    i.glyphicon.glyphicon-map-marker
    javascript:
      $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
        $(this).toggleClass('visible-xs text-center');
        $(this).find('i').toggleClass('glyphicon-chevron-right glyphicon-chevron-left');
        $('.row-offcanvas').toggleClass('active');
        $('#lg-menu').toggleClass('hidden-xs').toggleClass('visible-xs');
        $('#xs-menu').toggleClass('visible-xs').toggleClass('hidden-xs');
        $('#btnShow').toggle();
        });
      });